import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function Home() {
  const [isOfficePopupVisible, setIsOfficePopupVisible] = useState(false);

  return (
    <>
      <Head>
        <title>PixelPanic Studio - Soon!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="logo">
          <span></span>
          <span></span>
        </div>

        <h1>PixelPanic Studio</h1>
        <p>We’re still panicking on how to arrange our pixels, but we’ll be here soon.</p>

        <div className="form">
          <p>Want to stay in the know?</p>

          <form>
            <div className="input-wrapper">
              <input type="email" placeholder="Enter your email" />

              <button type="submit">
                <svg clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m14.523 18.787s4.501-4.505 6.255-6.26c.146-.146.219-.338.219-.53s-.073-.383-.219-.53c-1.753-1.754-6.255-6.258-6.255-6.258-.144-.145-.334-.217-.524-.217-.193 0-.385.074-.532.221-.293.292-.295.766-.004 1.056l4.978 4.978h-14.692c-.414 0-.75.336-.75.75s.336.75.75.75h14.692l-4.979 4.979c-.289.289-.286.762.006 1.054.148.148.341.222.533.222.19 0 .378-.072.522-.215z" fill-rule="nonzero"/></svg>
              </button>
            </div>
          </form>
        </div>

        <div className="office-link" onClick={() => setIsOfficePopupVisible((old) => !old)}>
          <span></span>

          <p>Office Livestream</p>
        </div>

        <div className={`office-popup ${isOfficePopupVisible ? 'show' : ''}`}>
          <span onClick={() => setIsOfficePopupVisible(false)}>
            <svg clip-rule="evenodd" fill-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="m12 10.93 5.719-5.72c.146-.146.339-.219.531-.219.404 0 .75.324.75.749 0 .193-.073.385-.219.532l-5.72 5.719 5.719 5.719c.147.147.22.339.22.531 0 .427-.349.75-.75.75-.192 0-.385-.073-.531-.219l-5.719-5.719-5.719 5.719c-.146.146-.339.219-.531.219-.401 0-.75-.323-.75-.75 0-.192.073-.384.22-.531l5.719-5.719-5.72-5.719c-.146-.147-.219-.339-.219-.532 0-.425.346-.749.75-.749.192 0 .385.073.531.219z"/></svg>
          </span>

          <Image src="/image-asset.gif" alt="PixelPanic Studio" width={700} height={400} />
        </div>
      </div>
    </>
  );
}
